Switch error state button visibility according to listener nullability
faberNovel/stateful-layout pull request #91
Opened 2020-09-21 09:45 UTC by kelianClerc

Fixes #90

2020-09-21 09:51 UTC, flolom requested changes
Please update `CHANGELOG.md`

2020-09-21 09:51 UTC, sjcqs reviewed
There are no tests at the moment but you could add some.

2020-09-21 11:38 UTC, sjcqs approved these changes

2020-09-21 15:10 UTC, flolom requested changes

2020-09-21 15:10 UTC, flolom commented on lib/src/main/ktx/com/fabernovel/statefullayout/StatefulLayout.kt
> +        setErrorRetryListener(onRetryListener)
BEFORE : You can override the error layout without providing a retry button AND pass a null `onRetryListener` by just calling the extension method `showError("error message")`

AFTER : If you do this, the `requireNotNull(retryButton)` in `private fun State.setErrorRetryListener` will be triggered and the app will crash

-> in `setErrorRetryListener` you need to check the requireNotNull only if `onRetryListener` is not null

2020-09-22 06:48 UTC, sjcqs commented
https://github.com/faberNovel/stateful-layout/pull/91#discussion_r492131248

As @f-lolom stated this change is incompatible with the current API. If ones needs to remove the retry button, he should override the default error state.

2020-09-22 06:48 UTC, closed without merging